### ISSUE TITLE
[BUG] fitHeight not set height

### ISSUE THREAD

**Issue by ArseniyXaoc** [tech-systems/panes#225]
If set fitHeight = true, 
The panel size becomes larger than the window size and goes down, the scrolling of the internal content does not appear.

`<div class="pane" style="transform: translateY(0px) translateZ(0px); height: unset; cursor: grab; transition: initial;"><ion-drawer style="display: block; transition: opacity 300ms ease 0s; overflow-x: hidden; height: unset; visibility: unset; pointer-events: unset;">`

**Comment by roman-rr** [comment]
@ArseniyXaoc Please share repo, code or reproduction environment on jsfiddle or similar, so I can help quickly.

**Comment by bghub1** [comment]
Hi @roman-rr I'm getting the same missing scroller issue when using fitHeight feature. It can be replicated on your auto height fiddle example https://jsfiddle.net/romantonoff/b4s5kjdr/ (just populate more text to trigger overflow)

![image](https://github.com/tech-systems/panes/assets/143032740/4f08c78b-468e-40ad-9b44-003e35087b9f)

**Comment by roman-rr** [comment]
@ArseniyXaoc @bghub1 
It should be fixed in tag `v.1.4.21` please try.

**Comment by bghub1** [comment]
Hi, @roman-rr I'm still experiencing the same issue after updating to 1.4.21. Scroller only seems to work properly if `FitHeightModule` module is disabled.

**Comment by roman-rr** [comment]
@bghub1 Sorry for late reply. Please check this example https://jsfiddle.net/romantonoff/xzg2aedq/
Here is scroll available from panne initialization, when the height is more than window. 
`fitHeight` is enabled on this example and version is 1.4.21 using.

**Comment by bghub1** [comment]
Hi, @roman-rr I've retested it and it's now working as expected 🎉 Thank you
